COMMAND_INJECTION_RULES = [
    {"pattern": "exec\\(", "reason": "The exec function can be used to execute arbitrary commands."},
    {"pattern": "shell_exec\\(", "reason": "The shell_exec function can be used to execute arbitrary commands."},
    {"pattern": "system\\(", "reason": "The system function can be used to execute arbitrary commands."},
    {"pattern": "passthru\\(", "reason": "The passthru function can be used to execute arbitrary commands."},
    {"pattern": "proc_open\\(", "reason": "The proc_open function can be used to execute arbitrary commands."},
    {"pattern": "pcntl_exec\\(", "reason": "The pcntl_exec function can be used to execute arbitrary commands."},
    {"pattern": "assert\\(", "reason": "The assert function can evaluate and execute arbitrary code."},
    {"pattern": "create_function\\(", "reason": "The create_function function can evaluate and execute arbitrary code."},
    {"pattern": "\`[^\`]+\`", "reason": "Using backticks can be used to execute arbitrary commands."},
    {"pattern": "popen\\(", "reason": "The popen function can be used to execute arbitrary commands."},
    {"pattern": "\$\w+\s*=\s*\"\s*\$[^\"]+", "reason": "Variable interpolation can lead to command injection."},
    {"pattern": "file_put_contents\\(.+,\s*\$_(GET|POST|REQUEST|COOKIE|SERVER)", "reason": "Writing unfiltered input to files can lead to command injection."},
    {"pattern": "fopen\\(.+,\s*['\"]w['\"]", "reason": "Opening files for writing with unfiltered input can lead to command injection."},
    {"pattern": "fwrite\\(", "reason": "Writing unfiltered input to files using fwrite can lead to command injection."},
    {"pattern": "move_uploaded_file\\(", "reason": "Improper handling of uploaded files can lead to command injection."},
    {"pattern": "\$_(GET|POST|REQUEST|COOKIE|SERVER)\[.+\]\s*\.=", "reason": "Appending unfiltered input to variables can lead to command injection."},
    {"pattern": "include\s+\$_", "reason": "Including files based on unfiltered input can lead to command injection."},
    {"pattern": "require\s+\$_", "reason": "Requiring files based on unfiltered input can lead to command injection."},
    {"pattern": "eval\\(", "reason": "The eval function can evaluate and execute arbitrary code."},
    {"pattern": "call_user_func\\(", "reason": "Misuse of call_user_func can lead to command injection."},
]
